version: "3.9"

services:
  # ğŸ—„ï¸ Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net


  # ğŸš€ Backend (tu aplicaciÃ³n Node.js)
  # backend:
  #   build: .
  #   container_name: node_backend
  #   restart: always
  #   command: npm run start:prod
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - backend_net

# ğŸ“¦ VolÃºmenes persistentes
volumes:
  postgres_data:

# ğŸŒ Red compartida
networks:
  backend_net:
